name: sport_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.8.1

dependencies:
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  cloud_functions: ^5.5.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  table_calendar: ^3.0.9
  provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" 
flutter:
  uses-material-design: true
