import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:SportTracker/models/exercise_block.dart';

/// Sauvegarde une course enregistrée dans le programme du jour.
class RunSaveService {
  static Future<void> saveRunToTodayProgram({
    required int durationSeconds,
    required double distanceKm,
    required double? avgSpeedKmh,
    required double? maxSpeedKmh,
    required double? maxAltitudeM,
    required double? minAltitudeM,
    required List<Map<String, dynamic>> route,
    required String todaybd,
    String? runTitle,
    String? runDescription,
  }) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    final durationMin = (durationSeconds / 60).ceil();
    final distanceStr = distanceKm >= 1
        ? '${distanceKm.toStringAsFixed(2)} km'
        : '${(distanceKm * 1000).round()} m';

    final userDoc = await FirebaseFirestore.instance
        .collection('users')
        .doc(user.uid)
        .get();
    final poids = (userDoc.data()?['poids'] ?? 70).toDouble();

    final runBlock = ExerciseBlock()
      ..type = 'running'
      ..subType = 'endurance'
      ..duration = durationMin.toString()
      ..distance = distanceStr
      ..intensity = 'moderate';
    final caloriesRun = runBlock.estimateCalories(poids: poids).round();

    final runExercise = <String, dynamic>{
      'type': 'running',
      'subType': 'endurance',
      'duration': durationMin.toString(),
      'distance': distanceStr,
      'intensity': 'moderate',
      'accompli': true,
      'recordedRun': true,
      'route': route,
      'durationSeconds': durationSeconds,
      'distanceKm': distanceKm,
      'caloriesRun': caloriesRun,
      if (avgSpeedKmh != null) 'avgSpeedKmh': avgSpeedKmh,
      if (maxSpeedKmh != null) 'maxSpeedKmh': maxSpeedKmh,
      if (maxAltitudeM != null) 'maxAltitudeM': maxAltitudeM,
      if (minAltitudeM != null) 'minAltitudeM': minAltitudeM,
      if (runTitle != null && runTitle.isNotEmpty) 'runTitle': runTitle,
      if (runDescription != null && runDescription.isNotEmpty) 'runDescription': runDescription,
    };

    final docRef = FirebaseFirestore.instance
        .collection('users')
        .doc(user.uid)
        .collection('programmes')
        .doc(todaybd);

    final doc = await docRef.get();
    final data = doc.data();
    final List<dynamic> exercices = List.from(data?['exercices'] ?? []);
    exercices.add(runExercise);

    final caloriesExos = _calculerCaloriesExercices(exercices, poids: poids);
    final caloriesPas = (data?['calories_pas'] ?? 0).toDouble();
    final bmrCalories = (data?['calories_repos'] ?? (poids * 24)).toDouble();
    final caloriesIngerees = data?['calories_ingerees'] ?? 0;

    if (doc.exists) {
      await docRef.update({
        'exercices': exercices,
        'calories_exercices': caloriesExos,
        'calories': caloriesPas + caloriesExos + bmrCalories,
      });
    } else {
      await docRef.set({
        'nom': 'Programme auto-généré',
        'commentaire': '',
        'jour': todaybd,
        'date': DateTime.now(),
        'pas': 0,
        'calories_pas': 0,
        'calories_exercices': caloriesExos,
        'calories_repos': bmrCalories,
        'calories': caloriesExos + bmrCalories,
        'calories_ingerees': caloriesIngerees,
        'exercices': exercices,
        'autoGenerated': true,
      });
    }
  }

  static double _calculerCaloriesExercices(List<dynamic> exercices,
      {required double poids}) {
    double total = 0;
    for (final ex in exercices) {
      if (ex is Map && (ex['accompli'] == true || ex['accompli'] == 1)) {
        final block = ExerciseBlock.fromMap(Map<String, dynamic>.from(ex));
        total += block.estimateCalories(poids: poids);
      }
    }
    return total.roundToDouble();
  }

  /// Supprime une course enregistrée du programme (retire l'exercice de la BD).
  static Future<void> deleteRecordedRun({
    required String programmeDocId,
    required int exerciseIndex,
  }) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    final docRef = FirebaseFirestore.instance
        .collection('users')
        .doc(user.uid)
        .collection('programmes')
        .doc(programmeDocId);

    final doc = await docRef.get();
    if (!doc.exists) return;

    final data = doc.data()!;
    final exercices = List<Map<String, dynamic>>.from(
      (data['exercices'] as List<dynamic>?)
          ?.map((e) => Map<String, dynamic>.from(e as Map)) ?? [],
    );
    if (exerciseIndex < 0 || exerciseIndex >= exercices.length) return;

    exercices.removeAt(exerciseIndex);

    final userDoc = await FirebaseFirestore.instance
        .collection('users')
        .doc(user.uid)
        .get();
    final poids = (userDoc.data()?['poids'] ?? 70).toDouble();
    final caloriesExos = _calculerCaloriesExercices(
        List<dynamic>.from(exercices), poids: poids);
    final caloriesPas = (data['calories_pas'] ?? 0).toDouble();
    final bmrCalories = (data['calories_repos'] ?? (poids * 24)).toDouble();

    await docRef.update({
      'exercices': exercices,
      'calories_exercices': caloriesExos,
      'calories': caloriesPas + caloriesExos + bmrCalories,
    });
  }
}
