// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpUpzn0Uu93rljcSWfKLR17LZAXKSTb0',
    appId: '1:778828345523:web:df1c06851f8f2fec3b00c6',
    messagingSenderId: '778828345523',
    projectId: 'sportracker80',
    authDomain: 'sportracker80.firebaseapp.com',
    storageBucket: 'sportracker80.firebasestorage.app',
    measurementId: 'G-R8XFHTVB89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqGpIwJptRhZlGV-v8_OM_gr383zYXRc8',
    appId: '1:778828345523:android:b2d5b93cb10003c93b00c6',
    messagingSenderId: '778828345523',
    projectId: 'sportracker80',
    storageBucket: 'sportracker80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyZcnsXE7i6O_xfiTTrPO-bK69j_54xI',
    appId: '1:778828345523:ios:ec2a8520194696063b00c6',
    messagingSenderId: '778828345523',
    projectId: 'sportracker80',
    storageBucket: 'sportracker80.firebasestorage.app',
    iosBundleId: 'com.example.sportTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyZcnsXE7i6O_xfiTTrPO-bK69j_54xI',
    appId: '1:778828345523:ios:ec2a8520194696063b00c6',
    messagingSenderId: '778828345523',
    projectId: 'sportracker80',
    storageBucket: 'sportracker80.firebasestorage.app',
    iosBundleId: 'com.example.sportTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOpUpzn0Uu93rljcSWfKLR17LZAXKSTb0',
    appId: '1:778828345523:web:78e8adc1c01164ff3b00c6',
    messagingSenderId: '778828345523',
    projectId: 'sportracker80',
    authDomain: 'sportracker80.firebaseapp.com',
    storageBucket: 'sportracker80.firebasestorage.app',
    measurementId: 'G-MY527R991G',
  );
}
